// Generated by CoffeeScript 1.10.0
(function() {
  var invariate, zappajs_plugin_css;

  invariate = require('invariate');

  module.exports = zappajs_plugin_css = function(modules) {
    var context, i, len, module, name, route;
    context = this.context, route = this.route;
    if (typeof modules === 'string') {
      modules = [modules];
    }
    for (i = 0, len = modules.length; i < len; i++) {
      name = modules[i];
      module = this.require(name);
      context[name] = invariate(function(k, v) {
        module.render(v, {
          filename: k
        }, function(err, css) {
          if (err) {
            throw err;
          }
          if ((css.css != null) && typeof css.css === 'string') {
            css = css.css;
          }
          return route({
            verb: 'get',
            path: k,
            handler: css,
            type: 'css'
          });
        });
      });
    }
  };

}).call(this);
